# Generated by Django 3.2.9 on 2021-12-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('blood_group', models.CharField(max_length=20)),
                ('zilla', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
