# Generated by Django 3.2.9 on 2021-12-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0002_blooddonor_last_donation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='medi.zilla')),
            ],
        ),
    ]
