# Generated by Django 3.2.9 on 2021-12-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0004_bloodgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('degree', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('chamber_address', models.CharField(max_length=100)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('active_days', models.CharField(max_length=100)),
                ('zilla', models.CharField(max_length=25)),
                ('upazila', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=30)),
                ('upazila', models.CharField(default='', max_length=25)),
                ('zilla', models.CharField(default='', max_length=25)),
                ('contact', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
