# Generated by Django 3.2.9 on 2021-12-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0005_auto_20211210_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chategory',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
