# Generated by Django 3.2.9 on 2021-12-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0007_category_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=30)),
                ('vehicle_no', models.CharField(default='', max_length=25)),
                ('upazila', models.CharField(default='', max_length=25)),
                ('zilla', models.CharField(default='', max_length=25)),
                ('contact', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
