# Generated by Django 3.2.9 on 2021-12-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0008_ambulance_ambulancetype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Hospital',
            new_name='Hospitals',
        ),
    ]
