# Generated by Django 3.2.9 on 2021-12-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0009_auto_20211210_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Hospitals',
        ),
    ]
