# Generated by Django 3.2.9 on 2021-12-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0010_auto_20211210_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='type',
            field=models.CharField(default='', max_length=45),
        ),
    ]
