# Generated by Django 3.2.9 on 2021-12-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0011_alter_ambulance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('open', models.CharField(default='', max_length=100)),
                ('upazila', models.CharField(default='', max_length=25)),
                ('zilla', models.CharField(default='', max_length=25)),
                ('contact', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
