# Generated by Django 3.2.9 on 2021-12-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0012_bloodbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=30)),
                ('upazila', models.CharField(default='', max_length=25)),
                ('zilla', models.CharField(default='', max_length=25)),
                ('contact', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
