# Generated by Django 3.2.9 on 2021-12-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0013_category_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('image', models.ImageField(default='', upload_to='medi/images')),
            ],
        ),
    ]
