# Generated by Django 3.2.9 on 2021-12-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0018_auto_20211220_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medi.bbcategory'),
        ),
    ]
